local BB = _G.BB

local CONSTANTS = {
    GRACE_PERIOD = 10,
    INTIMIDATE_DISTANCE = 1200,
    INTIMIDATE_ANGLE = 90,
    MARK_DISTANCE = 3000,
    MELEE_DISTANCE = 200,
    MELEE_ANGLE = 60,
    CONC_DISTANCE = 3000,
    CONC_ANGLE = 90,
    RELOAD_CHECK_INTERVAL = 0.5,
    MELEE_CHECK_INTERVAL = 0.1,
    CONC_COOLDOWN = 4,
    INTIMIDATE_COOLDOWN = 2,
    MARK_COOLDOWN = 2,
    INTIMIDATE_MAX_ATTEMPTS = 3,
    PRIORITY_TARGET_DURATION = 7,
    COOP_TEAMMATE_DANGER_RANGE = 1000,
    MAX_RELOADING_TEAMMATES = 2,
    PRIORITY_TARGET_CLAIM_TIMEOUT = 5,
    DOZER_FOCUS_REFRESH = 1,
    TARGET_SWITCH_DELAY = 0.5,
    COOP_REFRESH_INTERVAL = 0.1,
    TARGET_LOCK_MIN = 0.5,
    PRESSURE_SCAN_RANGE = 2000,
    PRESSURE_TEAMMATE_LOW_HEALTH_WEIGHT = 0.3,
    PRESSURE_SPECIAL_WEIGHT = 0.15,
    PRESSURE_ENEMY_WEIGHT = 0.05,
    PRESSURE_HIGH_THRESHOLD = 0.7,
    PRESSURE_LOW_THRESHOLD = 0.3,
    PRESSURE_RELOAD_MIN = 0.0,
    PRESSURE_RELOAD_MAX = 0.8,
    ASSIGNMENT_UPDATE_INTERVAL = 0.3,
    ASSIGNED_TARGET_BONUS = 600,
    CLUSTER_DISTANCE = 1000,
    UNASSIGNED_TARGET_BONUS = 100,
    OTHER_ASSIGNMENT_PENALTY = 0.3,
    LOW_HEALTH_TTK_BONUS = 1.5,
    TTK_SCORE_CAP = 10,
}

local THREAT_WEIGHTS = {
    DISTANCE_BASE = 1000,
    CLOAKER = 100,
    TASER = 90,
    SHIELD = 60,
    DOZER = 80,
    MEDIC = 70,
    SNIPER = 75,
    SPECIAL = 65,
    TURRET = 20,
    LOW_HEALTH_BONUS = 50,
    TARGETING_ME_BONUS = 60,
    SAME_TARGET_PENALTY = 0.35,
    DIRECTION_BONUS = 30,
    CAPTAIN_MINION = 110,
    CAPTAIN_VIP_SUPPRESSED = 5,
    DOZER_MEDIC_SYNERGY = 25,
    SHIELD_BLOCKED_PENALTY = 0.2,
    TASING_BONUS = 120,
    SPOOC_ATTACK_BONUS = 140,
    COOP_TURRET_PRIO = 8,
    COOP_DOZER_PRIO = 13,
    COOP_DOZER_FACING_BONUS = 20,
    COOP_TASER_PRIO = 14,
    COOP_CLOAKER_PRIO = 12,
    COOP_CLOAKER_CLOSE_PRIO = 18,
    COOP_SNIPER_PRIO = 15,
    COOP_SNIPER_FAR_BONUS = 20,
    COOP_MEDIC_PRIO = 20,
    COOP_TASING_PRIO = 30,
    COOP_SPOOC_PRIO = 28,
    COOP_SHIELD_BLOCKED_PRIO = 2,
    COOP_SHIELD_CLEAR_PRIO = 9,
    COOP_CLUSTER_BONUS = 5,
    COOP_VERIFIED_BONUS = 2,
}

local SLOTS = {
    PLAYERS = { 2, 3, 4, 5 },
    CRIMINALS_NO_DEPLOYABLES = { 2, 3, 16 },
    HOSTAGES = 22,
    TURRETS = 25,
}

local ENEMY_TWEAK_MAP = {
    shield = { shield = true },
    fbi_shield = { shield = true },
    heavy_swat_shield = { shield = true },
    tank = { dozer = true },
    tank_medic = { dozer = true, medic = true },
    tank_hw = { dozer = true },
    tank_mini = { dozer = true },
    taser = { taser = true },
    spooc = { cloaker = true },
    medic = { medic = true },
    sniper = { sniper = true },
    phalanx_vip = { captain = true },
    phalanx_minion = { captain = true },
    phalanx_vip_test = { captain = true },
    swat_turret_gun = { turret = true },
}

BB.CONSTANTS = CONSTANTS
BB.THREAT_WEIGHTS = THREAT_WEIGHTS
BB.SLOTS = SLOTS
BB.ENEMY_TWEAK_MAP = ENEMY_TWEAK_MAP